### ISSUE TITLE
Bug: outdated `#lastTimeRewardApplicable` tests

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#113]
In https://github.com/PrimeDAO/contracts/pull/111 tests in `staking-rewards.js:418` on `#lastTimeRewardApplicable` are failing. The tests were written for the previous version of the contract and might be outdated, more up-to-date tests are required. Older implementation could be taken as a reference:https://github.com/PrimeDAO/monorepo/blob/master/packages/contracts/test/staking-rewards.js

**Comment by codebuster22** [comment]
Received, will start soon with it.

**Comment by codebuster22** [comment]
Issue solved at PR #111 .
