### ISSUE TITLE
provide richer Seed state information, and avoid use of balanceOf

### ISSUE THREAD

**Issue by dkent600** [PrimeDAO/contracts#146]
We need to avoid using balanceOf to compute state in the Seed contract. State includes:

1. the number of seed tokens that are the max that can be distributed, same as the amount that is initially transferred into the contract
2. the number of Seed tokens that have been distributed
3. the number of Seed tokens remaining to be distributed

(having all three is nice, but technically, only need any of (1,2), (1,3) or (2,3)).

4. the total number of Funding tokens that have ever been contributed
5. the number of Funding tokens that have been withdrawn
6. the number of Funding tokens that remain after all withdrawals

(having all three is nice, but technically, only need any of (4,5), (4,6) or (5,6))

**Comment by codebuster22** [comment]
Hey @dkent600 , do you need a state to keep track of seed that have been claimed?
Also by distributed you mean buy or claim i.e. when a user buys the token or when the users claim them.

**Comment by dkent600** [comment]
> Hey @dkent600 , do you need a state to keep track of seed that have been claimed?

Yes thanks, that is what I meant by "distributed", sorry.

> Also by distributed you mean buy or claim i.e. when a user buys the token or when the users claim them.

It is easy enough to compute the # of seed tokens bought as a function of the number of funding tokens contributed and the "price" (the ratio between them).

**Comment by codebuster22** [comment]
Okay @dkent600 , I'll make the necessary updates.

**Comment by codebuster22** [comment]
So @dkent600 , should this state include the fee(that we collect when they claim). Because when a user claims, we are transferring the ```seedAmount``` to the user and the relevant ```fee``` to us.

**Comment by dkent600** [comment]
Good question.  I think it should include the fee because the max is == the # of tokens transferred to the contract at the beginning, from which the fee is drawn.

**Comment by codebuster22** [comment]
Okay
