### ISSUE TITLE
Optimize gas spending

### ISSUE THREAD

**Issue by BritikovKI** [PrimeDAO/contracts#147]
in `Seed.sol` in function `retrieveFundingToken` on line [243](https://github.com/PrimeDAO/contracts/blob/492a73ba308480d8580becc73391d6b607a63abb/contracts/seed/Seed.sol#L243) we are creating `Lock` variable, which is not necessary and which is eating part of our gas, i think we may just use the direct value from mapping

**Comment by codebuster22** [comment]
Okay, so should I directly use tokenLocks[_locker] everywhere?

**Comment by BritikovKI** [comment]
Not applicable anymore
