### ISSUE TITLE
Make Seed.buy return the amount of funding tokens expended

### ISSUE THREAD

**Issue by dkent600** [PrimeDAO/contracts#156]
Can we please make Seed.buy return the amount of funding tokens expended and the fee, as an array [amount, fee].

This enables dapps to `call` the function to anticipate the cost of buying x amount of seed tokens.

**Comment by dkent600** [comment]
This request may be ignored if we implement https://github.com/PrimeDAO/contracts/issues/158 instead

**Comment by codebuster22** [comment]
Working on #158. Closing this Issue.
