### ISSUE TITLE
Make Seed.claimLock return the amount of seed tokens rewarded

### ISSUE THREAD

**Issue by dkent600** [PrimeDAO/contracts#157]
Can we please make Seed.claimLock return the amount of seed tokens claimed and the fee, as an array [amount, fee].

This enables dapps to call the function to anticipate the result of claiming x amount of seed tokens.

**Comment by codebuster22** [comment]
the first index of return array - amount. It should not include the fee right?

**Comment by dkent600** [comment]
> the first index of return array - amount. It should not include the fee right?

Correct, thanks
