### ISSUE TITLE
Bug: overlapping Seed locks lose track of vesting amounts

### ISSUE THREAD

**Issue by dkent600** [PrimeDAO/contracts#60]
It appears that in a Seed one can have make any number of overlapping locks (contributions, buys — there seem to be multiple descriptors for that).

But it also seems that when, for example, you lock twice, the second before having claimed for the first, the contract loses track of the time that the first lock was vested, and thus the user loses any claim to the amount vested by the first lock up to that point.

**Comment by codebuster22** [comment]
I think this issue have already been taken care of at #117

**Comment by kinspotting** [comment]
fixed
