### ISSUE TITLE
Fix: change onlyOwner to onlyRewardDistribution in StakingRewards

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#72]
The StakingRewards contract inherits from the `Ownable` contract, and clones are created by calling `createClone`in `FarmFactory.sol:102` and then calling`initialize` on the new instance in `FarmFactory.sol:114`. The clone will not have its owner set, because the constructor of the `Ownable` contract is never called. In particular, this means that `setRewardDistribution`, which is guarded by `onlyOwner`, can never be called on these cloned contracts.

**Comment by BritikovKI** [comment]
Seems like it is already done, there is no `onlyOwner` in `StakingReward`
