### ISSUE TITLE
Fix: FarmFactory.changeParent ownership mgmt

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#75]
The `changeParent` method calls a `transferOwnership` method on the `newStakingRewards` contract.:

```
parent.transferOwnership(address(avatar));
```

This will only work if the current `FarmFactory` is the owner of `newParent` -which is sort of inconvenient as (presumably) the deployer of the parent contract would first need to transfer ownership to the `FarmFactory` before it can register it as the new basis for Staking rewards

`TODO`:
- Do not call `transferOwnership`, but instead check if the parent is already owned by the avatar before setting this a parent

**Comment by BritikovKI** [comment]
This issue was closed when I worked on tests in issue #77
