### ISSUE TITLE
Bug: fee value is calculated in fundingToken but paid in seedToken

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#80]
`Seed.sol:186`: the fee is paid in `seedToken`, but is calculated on line 166 on as a percentage of the amount of `fundingToken`. This is clearly a mistake. Secondly, the decision to pay the fee in the `seedtoken` leads to a potential loss of funds for the user, because the contract will run out of funds as it needs to pay `cap` amount of seed tokens to the buyers in addition to paying the fees to the beneficiary.

**Comment by codebuster22** [comment]
Taken care by Konstantine
