### ISSUE TITLE
Docs: inconsistency between docs and implementation for _amount in the buy()

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#86]
`Seed.sol:158`: the documentation says that `_amount` is "The amount of tokens to buy", as it should be according to the specifications but by the code. But in the code, `_amount` corresponds to the amount of `fundingTokens` that are being offered.

`TODO`:
- Fix either the documentation or the code

**Comment by codebuster22** [comment]
https://docs.google.com/document/d/1qgyr6ZbBFzXPRceBGdvvdJiYwSuXW1NWkkOrg6j1dRE/edit - Is this the Documentations which needs to change

**Comment by codebuster22** [comment]
The documentation in the code is correct. I'm closing this issue.
